name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: print hello
        run: echo "hello there"
      - name: print bye
        run: echo "bye"
